# Generated by Django 4.2 on 2024-07-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                verbose_name="Код подтверждения, который отправляется на почту",
            ),
        ),
    ]
