# Generated by Django 4.2.1 on 2024-08-16 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_rename_frequency_frequencyofmailing_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FrequencyOfMailing",
            new_name="Periodicity",
        ),
        migrations.RenameField(
            model_name="mailing",
            old_name="frequency_of_mailing",
            new_name="periodicity",
        ),
    ]
