# Generated by Django 5.0.6 on 2024-06-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="catalog",
            old_name="Category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="catalog",
            old_name="Description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="catalog",
            old_name="Image",
            new_name="image",
        ),
    ]
