# Generated by Django 4.2.1 on 2024-08-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    (
                        "may_cancel_publication_product",
                        "may cancel publication product",
                    ),
                    (
                        "can_change_description_product",
                        "can change description product",
                    ),
                    ("can_change_category_product", "can change category product"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="sign_publication_product",
            field=models.BooleanField(
                default=False, verbose_name="Признак публикации продукта"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Изображение(превью)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Наименование"),
        ),
        migrations.AlterField(
            model_name="product",
            name="purchase_price",
            field=models.IntegerField(verbose_name="Цена за покупку"),
        ),
    ]
